SELECT * FROM Myszy ORDER BY data_wydania DESC;
SELECT COUNT(nr_myszy) FROM Myszy;
DELETE FROM Myszy;

SELECT * FROM Myszy_Bolek;
DELETE FROM Myszy_Bolek;

SELECT * FROM Myszy_Rura;
DELETE FROM Myszy_Rura;

EXECUTE PRZYJMIJ_MYSZY_NA_STAN('BOLEK');
EXECUTE PRZYJMIJ_MYSZY_NA_STAN('RURA');

EXECUTE WYPLATA();